### ISSUE TITLE
The program runs a bit slow

### ISSUE THREAD

**Issue by chillaxv** [holderlb/Subdue#2]
Hi Dr. Holder,

I entered 8,000 nodes with 13,000 edges. I found that the program was running very slowly. I still had no results after running for one night. Is there any way to solve it?

Thank you for your code sharing!

**Comment by ghost** [comment]
The two main parameters that affect runtime are 'prune' and 'limit'. First, I would turn pruning on by adding the '--prune' option. Limit defaults to E/2, 6500 in your case, which is pretty big. I would try a smaller value, maybe 650 or 325, or even smaller just to get it to finish. You could also print out new best patterns as the program progresses by putting the following code at the top of the PatternListInsert function in Pattern.py:

if (len(patternList) > 0) and (newPattern.value > patternList[0].value):
        print("New best pattern:")
        newPattern.print_pattern("  ")

Hope that helps. This version of Subdue uses an NP-Complete version of subgraph isomorphism, so it can be slow, especially on very homogeneous graphs, i.e., graphs without much node and edge attribute diversity.

**Comment by chillaxv** [comment]
Thank you for your answer! I tried the graph of node and edge attribute diversity and it was faster.
